apiVersion: v1
kind: Pod

metadata:
  name: insecure-demo

spec:
  containers:
    - name: application
      image: nginx:latest

      securityContext:
        privileged: true
        runAsUser: 0
        allowPrivilegeEscalation: true
